---
version: 25.1.2.3-ha5
slug: clickhouse_hass
name: ClickHouse
description: >-
  ClickHouse is a high-performance column-oriented DBMS.
  It can be integrated with Home Assistant for storing, processing and quickly analyzing data.
  Use ClickHouse as a reliable storage of historical data on sensors, events and automations.
  This allows you to effectively analyze large volumes of information and create custom dashboards with instant analytics.
url: https://github.com/pessom/hass-addons/tree/main/clickhouse_hass
arch:
  - amd64
init: false
startup: services
boot: auto
map:
  - ssl
options:
  http_port: 8124
  tcp_port: 9000
  logging:
    level: information
    log_queries: false
  performance: {}
  security:
    default_password: ""
  storage: {}
schema:
  http_port: port?
  tcp_port: port?
  mysql_port: port?
  postgresql_port: port?

  logging:
    level: list(trace|debug|information|warning|error)?
    log_queries: bool?

  performance:
    max_connections: int?
    max_concurrent_queries: int?
    max_server_memory_usage: int?
    max_server_memory_usage_to_ram_ratio: float?
    background_pool_size: int?

  security:
    default_password: str?

  storage:
    max_table_size_to_drop: int?
    max_partition_size_to_drop: int?

ports:
  8124/tcp: 8124
  9000/tcp: 9000
  9004/tcp: 9004
  9005/tcp: 9005
ports_description:
  8124/tcp: "HTTP port"
  9000/tcp: "TCP (native) port"
  9004/tcp: "MySQL protocol port"
  9005/tcp: "PostgreSQL protocol port"
